import time


t = 'RIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKL'
s = open('wow.txt', 'r').readline()
before = time.time()
t += '~'
d = {}
length = len(t)
for i in range(length - 3, -1, -1):
    d[t[i]] = d.get(t[i], length - i - 2)
d[t[-1]] = length - 1
d[t[-2]] = d.get(t[-2], length - 1)
t = t[:-1]
elem = t[-1]
i = length - 2
k = 0
la = len(s)
while i < la:
    if s[i] != elem:
        i += d.get(s[i], d['~'])
    else:
        if s[i-length+2:i+1] == t:
            k = i-length+2
            break
        i += d[elem]
after = time.time()
print(k, after - before)

before = time.time()
k = s.find(t)
after = time.time()
print(k, after - before)

"""
RIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKLPANICAMALINSUKARIBADANHDFHFHHKKRKKLGLGLLGLLGLGLGLJKJKKJFKJKFJKJKJFKJFNVNNNNNVKJKJKFJDKJFKKJKVNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKFDFKJDJKFKDFJKDJKFJKDJFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFKDJFKDJFKJDKCNCKDNKNDVNLDKJKLFKLDJFKLJDFKLJDLFJFKL
"""

# what = 'print'
# file_name = 'test.py'
# new_line = False
# end = ')'
#
# if new_line:
#     what = what[:what.find('(')]
#
# can = False
# res = []
# d = {}
# what += '~'
# length = len(what)
# for i in range(length - 3, -1, -1):
#     d[what[i]] = d.get(what[i], length - i - 2)
# d[what[-1]] = length - 1
# d[what[-2]] = d.get(what[-2], length - 1)
# what = what[:-1]
# elem = what[-1]
#
# for line, s in enumerate(open(file_name, 'r').readlines()):
#     la = len(s)
#     k = -1
#     i = length - 2
#
#     # print(d)
#
#     while i < la:
#         if s[i] != elem:
#             i += d.get(s[i], d['~'])
#         else:
#             if s[i - length + 2:i + 1] == what:
#                 k = i - length + 2
#                 break
#             i += d[elem]
#     if k != -1:
#         res.append(line + 1)
#         if new_line and end not in s:
#             can = True
#     else:
#         if can:
#             if end in s:
#                 res.append(line + 1)
#                 can = False
#             else:
#                 res.append(line + 1)
# print(res)


"""
      
        for line, s in enumerate(open(file_name, 'r').readlines()):
            d = {}
            what += '~'
            length = len(what)
            for i in range(length - 3, -1, -1):
                d[what[i]] = d.get(what[i], length - i - 2)
            d[what[-1]] = length - 1
            d[what[-2]] = d.get(what[-2], length - 1)
            what = what[:-1]
            elem = what[-1]
            i = length - 2
            k = 0
            la = len(s)
            while i < la:
                if s[i] != elem:
                    i += d.get(s[i], d['~'])
                else:
                    if s[i - length + 2:i + 1] == what:
                        k = i - length + 2
                        break
                    i += d[elem]
            if k:
                return line + 1

"""

